version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=commcare_sync
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  web:
    image: commcare-sync_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    deploy:
      replicas: 3

  celery:
    image: commcare-sync_celery 
    command: celery -A commcare_sync worker -l INFO -B
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    deploy:
      replicas: 2

volumes:
  postgres_data:
  redis_data:
